version: "3"
services:
  phpstorm:
    container_name: creditcard_phpstorm
    build:
      context: docker/php
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: creditcard_mysql
      DB_PORT: 3306
      DB_DATABASE: creditcard
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - creditcard:/opt/creditcard:nocopy,delegated
    networks:
      - default
volumes:
  creditcard:
    external: true


